ManningsLootSystem::InventoryController
InventoryController ManningsLootSystem.InventoryController.instance
InventoryController ManningsLootSystem.InventoryController._instance
InventoryController ManningsLootSystem.InventoryController.Instance
Referenced by ManningsLootSystem.Loot.AddToInventory, ManningsLootSystem.Bow.Use.
int ManningsLootSystem.InventoryController._arrowCount
Referenced by ManningsLootSystem.Bow.Use.
int ManningsLootSystem.InventoryController.inventorySize
Referenced by ManningsLootSystem.InventoryController.AddToInventory, ManningsLootSystem.InventoryController.PopulateInventory, ManningsLootSystem.InventoryController.PopulateInventoryTiles, ManningsLootSystem.InventoryController.Start.
List<GameObject> ManningsLootSystem.InventoryController.inventoryItems
Referenced by ManningsLootSystem.InventoryController.AddToInventory, ManningsLootSystem.InventoryController.PopulateInventory.
int ManningsLootSystem.InventoryController.playerMoney
Referenced by ManningsLootSystem.InventoryController.BuyObject, ManningsLootSystem.InventoryController.SellObject.
int ManningsLootSystem.InventoryController.arrowCount
Referenced by ManningsLootSystem.InventoryController.UpdateArrows.
AudioClip ManningsLootSystem.InventoryController.collectLootSound
Referenced by ManningsLootSystem.InventoryController.AddPotion, ManningsLootSystem.InventoryController.AddToInventory, ManningsLootSystem.InventoryController.SellObject.
List<Potions> ManningsLootSystem.InventoryController.potions
Referenced by ManningsLootSystem.InventoryController.AddPotion, ManningsLootSystem.InventoryController.Awake, ManningsLootSystem.InventoryController.ShowInventory, ManningsLootSystem.InventoryController.Update.
GameObject ManningsLootSystem.InventoryController.inventoryObject
GameObject ManningsLootSystem.InventoryController.inventoryBox
Referenced by ManningsLootSystem.InventoryController.PopulateInventoryTiles.
GameObject ManningsLootSystem.InventoryController.selectedLoot
Referenced by ManningsLootSystem.InventoryController.Equip, ManningsLootSystem.InventoryController.RemoveFromInventory, ManningsLootSystem.InventoryController.SelectLoot.
GameObject ManningsLootSystem.InventoryController.scrollViewContent
Referenced by ManningsLootSystem.InventoryController.PopulateInventoryTiles.
List<GameObject> ManningsLootSystem.InventoryController.boxes
Referenced by ManningsLootSystem.InventoryController.PopulateInventory, ManningsLootSystem.InventoryController.SelectLoot.
TextMeshProUGUI ManningsLootSystem.InventoryController.infoBox
AudioSource ManningsLootSystem.InventoryController.audio
Referenced by ManningsLootSystem.InventoryController.Awake.
bool ManningsLootSystem.InventoryController.showingInventory
Referenced by ManningsLootSystem.InventoryController.ShowInventory, ManningsLootSystem.InventoryController.Update.
InventoryController ManningsLootSystem.InventoryController.inventoryInstance
Referenced by ManningsLootSystem.InventoryController.Awake.
void ManningsLootSystem.InventoryController.Start()
References ManningsLootSystem.InventoryController.inventorySize, ManningsLootSystem.InventoryController.PopulateInventoryTiles.
void ManningsLootSystem.InventoryController.Awake()
References ManningsLootSystem.InventoryController.audio, ManningsLootSystem.InventoryController.inventoryInstance, ManningsLootSystem.InventoryController.potions, ManningsLootSystem.InventoryController.Potions.potionType.
void ManningsLootSystem.InventoryController.Update()
References ManningsLootSystem.InventoryController.potions, ManningsLootSystem.InventoryController.Potions.quantityOwned, ManningsLootSystem.InventoryController.showingInventory, ManningsLootSystem.InventoryController.ShowInventory, ManningsLootSystem.InventoryController.Potions.usePotionButton.
bool ManningsLootSystem.InventoryController.AddToInventory(GameObject loot)
References ManningsLootSystem.InventoryController.collectLootSound, ManningsLootSystem.InventoryController.inventoryItems, ManningsLootSystem.InventoryController.inventorySize, ManningsLootSystem.InventoryController.PopulateInventory.
Referenced by ManningsLootSystem.Loot.AddToInventory.
void ManningsLootSystem.InventoryController.RemoveFromInventory()
References ManningsLootSystem.InventoryController.PopulateInventory, ManningsLootSystem.InventoryController.selectedLoot.
void ManningsLootSystem.InventoryController.SellObject(int moneyRecieved)
References ManningsLootSystem.InventoryController.collectLootSound, ManningsLootSystem.InventoryController.playerMoney.
void ManningsLootSystem.InventoryController.BuyObject(int moneySpent)
References ManningsLootSystem.InventoryController.playerMoney.
void ManningsLootSystem.InventoryController.UpdateArrows(int arrowChange)
References ManningsLootSystem.InventoryController.arrowCount.
void ManningsLootSystem.InventoryController.AddPotion(Potion pot)
References ManningsLootSystem.InventoryController.collectLootSound, ManningsLootSystem.InventoryController.potions.
void ManningsLootSystem.InventoryController.PopulateInventory()
References ManningsLootSystem.InventoryController.boxes, ManningsLootSystem.InventoryController.inventoryItems, ManningsLootSystem.InventoryController.inventorySize.
Referenced by ManningsLootSystem.InventoryController.AddToInventory, ManningsLootSystem.InventoryController.PopulateInventoryTiles, ManningsLootSystem.InventoryController.RemoveFromInventory, ManningsLootSystem.InventoryController.ShowInventory.
void ManningsLootSystem.InventoryController.SelectLoot(GameObject loot)
References InventoryBox._linkedLoot, ManningsLootSystem.InventoryController.boxes, ManningsLootSystem.InventoryController.selectedLoot.
void ManningsLootSystem.InventoryController.Equip()
References ManningsLootSystem.InventoryController.selectedLoot.
void ManningsLootSystem.InventoryController.ShowInventory(bool show)
References ManningsLootSystem.InventoryController.PopulateInventory, ManningsLootSystem.InventoryController.potions, ManningsLootSystem.InventoryController.showingInventory.
Referenced by ManningsLootSystem.InventoryController.Update.
void ManningsLootSystem.InventoryController.PopulateInventoryTiles()
References ManningsLootSystem.InventoryController.inventoryBox, ManningsLootSystem.InventoryController.inventorySize, ManningsLootSystem.InventoryController.PopulateInventory, ManningsLootSystem.InventoryController.scrollViewContent.
Referenced by ManningsLootSystem.InventoryController.Start.