EnemyController
Rigidbody2D EnemyController.myRigidbody
Referenced by Start.
bool EnemyController.moving
Referenced by Update.
float EnemyController.timeBetweenMoveCounter
Referenced by Start, Update.
float EnemyController.timeToMoveCounter
Referenced by Start, Update.
Vector3 EnemyController.moveDirection
Referenced by Update.
Transform EnemyController.target
Referenced by Start, Update.
float EnemyController.speed
Referenced by FollowPlayer.
float EnemyController.range
Referenced by Update.
int EnemyController.damage
Referenced by OnTriggerEnter2D, TakeDamage.
int EnemyController.health
Referenced by TakeDamage.
float EnemyController.moveSpeed
Referenced by Update.
float EnemyController.timeBetweenMove
Referenced by Start, Update.
float EnemyController.timeToMove
Referenced by Start, Update.
void EnemyController.Start()
References myRigidbody, target, timeBetweenMove, timeBetweenMoveCounter, timeToMove, timeToMoveCounter.
void EnemyController.Update()
References FollowPlayer, moveDirection, moveSpeed, moving, range, target, timeBetweenMove, timeBetweenMoveCounter, timeToMove, timeToMoveCounter.
void EnemyController.Die()
Referenced by TakeDamage.
void EnemyController.OnTriggerEnter2D(Collider2D other)
References damage, TakeDamage.
void EnemyController.FollowPlayer()
References speed.
Referenced by Update.
void EnemyController.TakeDamage(int damage)
References damage, Die, health.
Referenced by OnTriggerEnter2D.