PlayerController
PlayerController PlayerController.instance
PlayerController PlayerController._instance
PlayerController PlayerController.playerInstance
Referenced by Awake.
PlayerController PlayerController.Instance
Referenced by Decoration.Update.
int PlayerController._maxHealth
int PlayerController._currentHealth
bool PlayerController._canDash
int PlayerController._playerLevel
int PlayerController._experienceGained
int PlayerController._experienceToLevelUp
int PlayerController.maxHealth
Referenced by DeathTimer, LevelUp, LoseDeathPenalty, Start.
int PlayerController.baseHealth
Referenced by Start.
int PlayerController.currentHealth
Referenced by DeathTimer, LevelUp, TakeDamage.
int PlayerController.healthLostOnDeath
Referenced by DeathTimer, LoseDeathPenalty.
bool PlayerController.isRespawning
Referenced by DeathTimer, Travel, Update.
bool PlayerController.beenPlaced
Referenced by OnSceneLoaded, Update.
float PlayerController.dashCoolDownTime
Referenced by DashTimer, LevelUp.
bool PlayerController.canDash
Referenced by DashTimer, LevelUp, OnSceneLoaded, SetDashLocation, Update.
bool PlayerController.isDashing
Referenced by OnCollisionEnter2D, OnTriggerStay2D, SetDashLocation, Update.
float PlayerController.dashSpeed
Referenced by Update.
int PlayerController.dashDamage
Referenced by LevelUp, OnCollisionEnter2D.
LayerMask PlayerController.dashObstacles
Referenced by SetDashLocation.
GameObject PlayerController.dashHitParticles
Vector3 PlayerController.dashLocation
Referenced by SetDashLocation, Update.
string PlayerController.levelToRespawnIn
Referenced by DeathTimer.
string PlayerController.travelLocation
Referenced by Travel, Update.
float PlayerController.fallSpeed
Referenced by Update.
bool PlayerController.isFalling
Referenced by DeathTimer, OnSceneLoaded, OnTriggerStay2D, Update.
Vector3 PlayerController.fallPos
Referenced by OnTriggerStay2D, Update.
GameObject PlayerController.deadBody
Referenced by Die, OnTriggerStay2D.
int PlayerController.playerLevel
Referenced by LevelUp.
int PlayerController.experienceGained
Referenced by GainExperience, LevelUp.
int PlayerController.experienceToLevelUp
Referenced by GainExperience, LevelUp.
int PlayerController.healthGainOnLevelUp
Referenced by LevelUp.
float PlayerController.dashTimerDecreaseOnLevel
Referenced by LevelUp.
int PlayerController.dashDamageIncreaseOnLevel
Referenced by LevelUp.
float PlayerController.dashDistance
Referenced by Update.
int PlayerController.experienceRequiredPercentageIncrease
Referenced by LevelUp.
GameObject PlayerController.levelUpEffects
GameObject PlayerController.canDashparticles
AudioClip PlayerController.levelUpSound
Referenced by LevelUp, OnTriggerEnter2D.
List<AudioClip> PlayerController.hitSounds
AudioClip PlayerController.lootCollectedSound
AudioClip PlayerController.dashSound
Referenced by SetDashLocation.
AudioClip PlayerController.canDashSound
Referenced by DashTimer.
bool PlayerController.dashInMouseDirection
Referenced by Awake, ChangeDashType, Update.
double PlayerController.test
override void PlayerController.Awake()
References dashInMouseDirection, playerInstance.
virtual void PlayerController.Start()
References TwoDimensionalPlayerMovement.audio, baseHealth, maxHealth, OnSceneLoaded.
void PlayerController.OnSceneLoaded(Scene scene, LoadSceneMode mode)
References beenPlaced, canDash, TwoDimensionalPlayerMovement.canMove, isFalling.
Referenced by Start.
override void PlayerController.Update()
References beenPlaced, canDash, TwoDimensionalPlayerMovement.canMove, dashDistance, dashInMouseDirection, dashLocation, dashSpeed, fallPos, fallSpeed, isDashing, isFalling, isRespawning, TwoDimensionalPlayerMovement.moveDirection, SetDashLocation, EntryPoint.spawnDirection, travelLocation.
IEnumerator PlayerController.DashTimer()
References canDash, canDashSound, dashCoolDownTime.
Referenced by SetDashLocation.
override void PlayerController.OnCollisionEnter2D(Collision2D col)
References TwoDimensionalPlayerMovement.canMove, dashDamage, isDashing, TakeDamage.
void PlayerController.OnTriggerEnter2D(Collider2D col)
References levelUpSound, LoseDeathPenalty.
void PlayerController.OnTriggerStay2D(Collider2D col)
References Chasm._fallDirection, TwoDimensionalPlayerMovement.canMove, deadBody, DeathTimer, fallPos, isDashing, isFalling, Travel.
void PlayerController.Travel(Collider2D col)
References EntryPoint._linkedScene, isRespawning, travelLocation.
Referenced by OnTriggerStay2D.
void PlayerController.LevelUp()
References canDash, currentHealth, dashCoolDownTime, dashDamage, dashDamageIncreaseOnLevel, dashTimerDecreaseOnLevel, experienceGained, experienceRequiredPercentageIncrease, experienceToLevelUp, healthGainOnLevelUp, levelUpSound, maxHealth, playerLevel.
Referenced by GainExperience.
void PlayerController.LoseDeathPenalty()
References healthLostOnDeath, maxHealth.
Referenced by OnTriggerEnter2D.
virtual void PlayerController.Die()
References TwoDimensionalPlayerMovement.canMove, deadBody, DeathTimer.
Referenced by TakeDamage.
void PlayerController.SetDashLocation()
References canDash, TwoDimensionalPlayerMovement.canMove, dashLocation, dashObstacles, dashSound, DashTimer, TwoDimensionalPlayerMovement.direction, isDashing.
Referenced by Update.
IEnumerator PlayerController.DeathTimer()
References currentHealth, healthLostOnDeath, isFalling, isRespawning, levelToRespawnIn, maxHealth.
Referenced by Die, OnTriggerStay2D.
virtual void PlayerController.TakeDamage(int damage)
References currentHealth, Die.
Referenced by OnCollisionEnter2D.
void PlayerController.GainExperience(int experience)
References experienceGained, experienceToLevelUp, LevelUp.
virtual void PlayerController.ChangeDashType(bool type)
References dashInMouseDirection.