Spriter2UnityDX::EntityRenderer
SpriteRenderer [] Spriter2UnityDX.EntityRenderer.renderers
Referenced by Spriter2UnityDX.EntityRenderer.DoForAll, Spriter2UnityDX.EntityRenderer.RefreshRenders.
SortingOrderUpdater [] Spriter2UnityDX.EntityRenderer.updaters
Referenced by Spriter2UnityDX.EntityRenderer.RefreshRenders.
SpriteRenderer Spriter2UnityDX.EntityRenderer._first
Referenced by Spriter2UnityDX.EntityRenderer.RefreshRenders.
int Spriter2UnityDX.EntityRenderer.sortingOrder
bool Spriter2UnityDX.EntityRenderer.applySpriterZOrder
SpriteRenderer Spriter2UnityDX.EntityRenderer.first
Color Spriter2UnityDX.EntityRenderer.Color
Material Spriter2UnityDX.EntityRenderer.Material
int Spriter2UnityDX.EntityRenderer.SortingLayerID
string Spriter2UnityDX.EntityRenderer.SortingLayerName
int Spriter2UnityDX.EntityRenderer.SortingOrder
bool Spriter2UnityDX.EntityRenderer.ApplySpriterZOrder
void Spriter2UnityDX.EntityRenderer.Awake()
References Spriter2UnityDX.EntityRenderer.RefreshRenders.
void Spriter2UnityDX.EntityRenderer.OnEnable()
References Spriter2UnityDX.EntityRenderer.DoForAll.
void Spriter2UnityDX.EntityRenderer.OnDisable()
References Spriter2UnityDX.EntityRenderer.DoForAll.
void Spriter2UnityDX.EntityRenderer.DoForAll(Action< SpriteRenderer > action)
References Spriter2UnityDX.EntityRenderer.renderers.
Referenced by Spriter2UnityDX.EntityRenderer.OnDisable, Spriter2UnityDX.EntityRenderer.OnEnable.
void Spriter2UnityDX.EntityRenderer.RefreshRenders()
References Spriter2UnityDX.EntityRenderer._first, Spriter2UnityDX.EntityRenderer.renderers, Spriter2UnityDX.EntityRenderer.updaters.
Referenced by Spriter2UnityDX.EntityRenderer.Awake.